#!/usr/bin/env bash
# Render the prompt across known fixtures and write a markdown report.
#
# The report is the artifact the CI workflow turns into a PR comment, but
# it's a plain markdown file -- locally you can just `cat` it after the
# test runs. There is no GitHub-specific code here.
#
# Assertions are intentionally structural rather than golden-diff: a
# rendered prompt must be non-empty, and on the clean-git fixture it must
# contain the branch name. We can tighten to byte-for-byte goldens later;
# for now, the report is the human review surface.
set -euo pipefail

echo "Rendering prompt fixtures and writing PR report"
source "$DOTFILES_TEST_LIB"

if ! command -v zsh >/dev/null 2>&1; then
  die "zsh is not installed"
fi
if ! command -v perl >/dev/null 2>&1; then
  die "perl is not installed (needed for ANSI stripping)"
fi
if ! command -v git >/dev/null 2>&1; then
  die "git is not installed (needed for fixture setup)"
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROMPT_DIR="$ROOT_DIR/test/prompt"
log_dir="${DOTFILES_TEST_LOG_DIR:-$HOME/test-logs}"
mkdir -p "$log_dir"

report="$log_dir/prompt-report.md"
{
  echo "## zsh prompt render"
  echo
  echo "_Generated by \`test/tests.d/33-prompt-render.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ)._"
  echo
  printf "Host: \`%s\`  •  zsh: \`%s\`\n\n" \
    "$(uname -srm)" \
    "$(zsh --version | head -1)"
} >"$report"

render_one() {
  local fixture="$1" title="$2"
  local raw="$log_dir/render-${fixture}.raw"
  local err="$log_dir/render-${fixture}.err"

  info "Rendering fixture: $fixture"
  if ! zsh "$PROMPT_DIR/render.zsh" "$fixture" >"$raw" 2>"$err"; then
    warn "see $err"
    return 1
  fi

  local plain
  plain=$(zsh -c "source '$PROMPT_DIR/lib.zsh'; strip_ansi" <"$raw")

  {
    echo "<details><summary><strong>${title}</strong></summary>"
    echo
    echo '```text'
    printf '%s\n' "$plain"
    echo '```'
    echo
    echo "</details>"
    echo
  } >>"$report"

  # Echo the plain output for the caller to assert against.
  printf '%s' "$plain"
}

clean_render=$(render_one clean-git "Clean git repo on \`master\`")

if [ -z "$clean_render" ]; then
  warn "see $log_dir/render-clean-git.raw"
  die "clean-git fixture produced no rendered output"
fi

# The vcs segment should surface 'master' somewhere when CWD is a clean
# repo on that branch. If it doesn't, either p10k's vcs segment is broken
# or the fixture isn't actually a git repo (zsh failed to cd into it).
if ! printf '%s' "$clean_render" | grep -Fq 'master'; then
  warn "see $log_dir/render-clean-git.raw"
  warn "rendered (ANSI-stripped):"
  printf '%s\n' "$clean_render" >&2
  die "clean-git render does not contain 'master' -- vcs segment may be broken"
fi

info "report: $report"
info "render assertions passed"
